### PR TITLE
Add ManageWikiSettings and also make ManageWiki a landing page

### PR DESCRIPTION
**Pull request by paladox**
ManageWiki landing page was done by @MacFan4000. Im just copying the code from test server to a pull request.

### CODE REVIEW

**Comment by MacFan4000** [comment]
Why revert all the changes? @paladox

**Comment by paladox** [comment]
see irc staff channel, and im not reverting any thing just re adding things per discussion.

**Comment by MacFan4000** [comment]
@paladox looking at the diff we are changing barely anything now

**Comment by paladox** [comment]
@MacFan4000 are you sure? Because i can see your changes in the diff.

**Comment by paladox** [comment]
@MacFan4000 https://github.com/miraheze/ManageWiki/pull/19/files#diff-a1c4356635fb3d8761ebb8132316bda9R148

**Comment by MacFan4000** [comment]
Will merge on one hour if nobody objects

**Comment by paladox** [comment]
I would like @JohnFLewis to comment one last time before merging please.

**Comment by JohnFLewis** [comment]
Seems fine

**Pull request merged**
