### PR TITLE
Remove permission cache file when deleting or renaming a wiki

### PR DESCRIPTION
**Pull request by paladox**

### CODE REVIEW

**Comment by JohnFLewis** [comment]
Why isn’t this in the if?

**Comment by JohnFLewis** [comment]
Also there needs to be an if $var too inside the existing if

**Comment by paladox** [comment]
@JohnFLewis to prevent it throwing a error if the file does not exist.

**Comment by JohnFLewis** [comment]
Why recursive though?

**Comment by JohnFLewis** [comment]
Also that doesn’t stop an error?

**Comment by paladox** [comment]
@JohnFLewis done, it is a force of nature :P

**Pull request merged**
