### PR TITLE
add !empty check to avoid warning if overridedefault = []

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Comment by JohnFLewis** [comment]
Why use [] for no override instead of the traditional false which is consistent with probably what is in LS and all other settings?

**Comment by Universal-Omega** [comment]
> Why use [] for no override instead of the traditional false which is consistent with probably what is in LS and all other settings?

[] is used elsewhere also (in MWS, and in  LS sometimes also, I think) If the default in extension/core is equal to [] chances are thats what LS/MWS default is set to.

**Comment by JohnFLewis** [comment]
In the context of namespaces here though, no overrides == false, so should be using false not an empty array in my opinion.

**Comment by Universal-Omega** [comment]
> In the context of namespaces here though, no overrides == false, so should be using false not an empty array in my opinion.

That might be true, although I do still think this check should be added to avoid warnings in the future if it is accidentally added again. But if you don't think so, feel free to close this PR and I'll fix mw-config.

**Comment by JohnFLewis** [comment]
"if it is accidentally added again." then we want errors surely - it's misconfiguration?

**Comment by Universal-Omega** [comment]
> "if it is accidentally added again." then we want errors surely - it's misconfiguration?

Fair enough. Thanks!

**Pull request closed without merging**
