### PR TITLE
Add $wgManageWikiPermissionsBlacklistRightsDefault

### PR DESCRIPTION
**Pull request by bonnedav**
Rights listed here cannot be added to/removed from * but can be added to/removed from other groups.

### CODE REVIEW

**Comment by JohnFLewis** [comment]
This is super specific code for a group. A correct solution would be a single param managing the ability to do it for every group on a configurable basis.

There is no real reason to add a new param to manage the ability to control rights blacklisted from a single group while ignoring every other group. Also "Default" implies something different entirely.

**Comment by bonnedav** [comment]
I changed it to $wgManageWikiPermissionsBlacklistRightsAnon

**Comment by JohnFLewis** [comment]
I still don't feel like it's the right solution. The existing param should be extended to be configurable per group otherwise we'd need to add an infinite number of params for every group that shouldn't have a certain right assigned.

**Comment by bonnedav** [comment]
It's a workaround. What other groups shouldn't have certain rights assigned?

**Comment by JohnFLewis** [comment]
None that I know of but effective development is designing smart from the start.

One of the issues Miraheze has had with exts in the past is poor development/not smart development and the predecessors suffered from it badly. Since I have no intention to do this, merging code waiting for someone who won't doing a smart implementation is merging unsmart code.


The advantage is, as said before near non-existent as you can assign the rights already in LS without any issue.

**Comment by bonnedav** [comment]
This will work for now and it's easy to revert if a better solution is made in the future. I don't see how this could cause future headache. It allows you to set the rights yourself and makes the system more complete. It should even save time since the admins won't have to intervene and we won't have to wait.

**Comment by JohnFLewis** [comment]
I'm going to let someone else decide but in my opinion;
* it's a solution for a non problem,
* it's something we, as a platform, chose we want to handle through LS,
* doesn't make the product more complete as anyone wanting to use this ext can just not use this param and it won't actually affect the end result

**Comment by Reception123** [comment]
@bonnedav Could you give some examples of a right that anons, in your opinion should not be granted? And also, if bureaucrats are the ones who request this, why can't they just not add the permissions to anon in the first place, rather than requesting a restriction?

**Comment by bonnedav** [comment]
@bonnedav I am requesting an un-restriction. The skipcaptcha and torunblocked permissions are restricted because they should not be given to anons. This will allow them to be manageable for all groups except anon. so you can remove the restriction.

**Pull request closed without merging**
