### PR TITLE
Remove all users from groups when group no longer exists

### PR DESCRIPTION
**Pull request by Universal-Omega**

### CODE REVIEW

**Comment by JohnFLewis** [comment]
https://github.com/miraheze/ManageWiki/blob/master/includes/helpers/ManageWikiPermissions.php#L153

**Comment by Universal-Omega** [comment]
> https://github.com/miraheze/ManageWiki/blob/master/includes/helpers/ManageWikiPermissions.php#L153

Doesn't work then. I've tried

> https://github.com/miraheze/ManageWiki/blob/master/includes/helpers/ManageWikiPermissions.php#L153

That doesn't work. Not if doing from ManageWikiExtensions, or from ManageWikiPermissions, at least doesn't seem to, to me.

**Comment by dmehus** [comment]
This is a good idea in //theory//, if we can find a way to make it work. If //not//, should we have a prompt to users to remove users from extension-added user groups first before removing the extension?

**Comment by Universal-Omega** [comment]
> This is a good idea in _theory_, if we can find a way to make it work. If //not//, should we have a prompt to users to remove users from extension-added user groups first before removing the extension?

I tested this before pushing the PR, it does work this way.

**Comment by JohnFLewis** [comment]
> > https://github.com/miraheze/ManageWiki/blob/master/includes/helpers/ManageWikiPermissions.php#L153
> 
> That doesn't work. Not if doing from ManageWikiExtensions, or from ManageWikiPermissions, at least doesn't seem to, to me.

Then that should be made to work, not implementing another method while not considering the existing method.

**Pull request closed without merging**
